name: manual trigger

on:
  workflow_dispatch:
    inputs:
      askName:
        required: true
        type: string
        default: "Stranger"
        description: "Hello There, What's your name !!"
    

jobs:
  manual_timecheck:
    runs-on: ubuntu-slim
    steps:
      - name: time_check
        run: date
      - name: greet
        run: echo "Hello ${{ inputs.askName }}"
      - name: "Check Host Name"
        run: hostname
  check_selfhosted:
    runs-on: self-hosted
    steps:
      - name: "Check Host Name"
        run: hostname
      
